/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.projetomap.view;

import br.edu.projetomap.dao.AlunoDAO;
import br.edu.projetomap.model.Aluno;
import br.edu.projetomap.util.DateUtil;
import br.edu.projetomap.util.MensagensUtil;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rogerio
 */
public class AlunosJFrame extends javax.swing.JFrame {

    private AlunoDAO alunoDAO = new AlunoDAO();
    private Aluno alunoSelecionado;

    public Aluno getAlunoSelecionado() {
        return alunoSelecionado;
    }

    public void setAlunoSelecionado(Aluno alunoSelecionado) {
        this.alunoSelecionado = alunoSelecionado;
    }

    /**
     * Creates new form Alunos
     */
    public AlunosJFrame() {
        initComponents();
        setProperties();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlunos = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAluno = new javax.swing.JMenu();
        menuCadastrarAluno = new javax.swing.JMenuItem();
        menuTurma = new javax.swing.JMenu();
        menuListarTurma = new javax.swing.JMenuItem();
        menuLinguagem = new javax.swing.JMenu();
        menuPortugues = new javax.swing.JMenuItem();
        menuIngles = new javax.swing.JMenuItem();
        menuEspanhol = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatorioAlunos = new javax.swing.JMenuItem();
        menuRelatorioTurmas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Alunos");

        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        tableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlunos);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        menuAluno.setText("Aluno");

        menuCadastrarAluno.setText("Cadastrar");
        menuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAlunoActionPerformed(evt);
            }
        });
        menuAluno.add(menuCadastrarAluno);

        jMenuBar1.add(menuAluno);

        menuTurma.setText("Turma");

        menuListarTurma.setText("Listar");
        menuListarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarTurmaActionPerformed(evt);
            }
        });
        menuTurma.add(menuListarTurma);

        jMenuBar1.add(menuTurma);

        menuLinguagem.setText("Linguagem");

        menuPortugues.setText("pt_BR");
        menuPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPortuguesActionPerformed(evt);
            }
        });
        menuLinguagem.add(menuPortugues);

        menuIngles.setText("en_US");
        menuIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInglesActionPerformed(evt);
            }
        });
        menuLinguagem.add(menuIngles);

        menuEspanhol.setText("es_ES");
        menuEspanhol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEspanholActionPerformed(evt);
            }
        });
        menuLinguagem.add(menuEspanhol);

        jMenuBar1.add(menuLinguagem);

        menuRelatorios.setText("Relatorios");

        menuRelatorioAlunos.setText("Alunos");
        menuRelatorios.add(menuRelatorioAlunos);

        menuRelatorioTurmas.setText("Turmas");
        menuRelatorios.add(menuRelatorioTurmas);

        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(txtBusca)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAlunoActionPerformed
        alunoSelecionado = null;
        AlunoJFrame janela = new AlunoJFrame(this);
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setVisible(true);
    }//GEN-LAST:event_menuCadastrarAlunoActionPerformed

    public void preencherTabela(List<Aluno> param) {

        try {

            List<Aluno> lista = (param == null) ? alunoDAO.listar() : param;

            DefaultTableModel model = new DefaultTableModel();

            model.setColumnCount(4);
            model.setColumnIdentifiers(new String[]{
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_CPF), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_NOME), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_DATACADASTRO), 
                MensagensUtil.getString(MensagensUtil.MSG_TABELA_AULA)});
            model.setRowCount(lista.size());

            for (int i = 0; i < lista.size(); i++) {
                model.setValueAt(lista.get(i).getCpf(), i, 0);
                model.setValueAt(lista.get(i).getNome(), i, 1);
                model.setValueAt(DateUtil.dateToString(lista.get(i).getDataCadastro()), i, 2);
                model.setValueAt(lista.get(i).getTurma().getAula(), i, 3);
            }

            tableAlunos.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        String busca = txtBusca.getText();

        try {
            List<Aluno> resultado = alunoDAO.buscar(busca);
            preencherTabela(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void tableAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlunosMouseClicked

        // retorna a linha da tabela onde o clique ocorreu
        int row = tableAlunos.rowAtPoint(evt.getPoint());
        // retorna o código do cliente selecionado
        String cpf = (String) tableAlunos.getModel().getValueAt(row, 0);

        try {
            alunoSelecionado = alunoDAO.buscarPorCpf(cpf);

            System.out.println(alunoSelecionado);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tableAlunosMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if (alunoSelecionado != null) {
            try {

                int op = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir " + alunoSelecionado.getNome(), "Excluir", JOptionPane.OK_CANCEL_OPTION);
                if (op == JOptionPane.OK_OPTION) {
                    alunoDAO.excluir(alunoSelecionado);
                    preencherTabela(null);
                    alunoSelecionado = null;
                }

            } catch (Exception ex) {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    private void setProperties(){
        menuAluno.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_ALUNO));
        menuLinguagem.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_LINGUAGEM));
        menuTurma.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_TURMA));
        menuRelatorios.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_RELATORIO));
        menuCadastrarAluno.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_CADASTRAR));
        menuListarTurma.setText(MensagensUtil.getString(MensagensUtil.MSG_MENU_LISTAR));
        menuRelatorioAlunos.setText(MensagensUtil.getString(MensagensUtil.MSG_RELATORIO_LISTA_ALUNO));
        menuRelatorioTurmas.setText(MensagensUtil.getString(MensagensUtil.MSG_RELATORIO_LISTA_TURMA));
        lblTitulo.setText(MensagensUtil.getString(MensagensUtil.MSG_LABEL_ALUNOS));
        btnEditar.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_EDITAR));
        btnExcluir.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_EXCLUIR));
        btnSair.setText(MensagensUtil.getString(MensagensUtil.MSG_BUTTON_SAIR));
        
        preencherTabela(null);
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        if (alunoSelecionado != null) {

            AlunoJFrame janela = new AlunoJFrame(this);
            janela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, MensagensUtil.getString(MensagensUtil.MSG_ERRO_SELECIONAR));
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void menuListarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarTurmaActionPerformed
        TurmasJFrame janela = new TurmasJFrame();
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setVisible(true);
    }//GEN-LAST:event_menuListarTurmaActionPerformed

    private void menuPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPortuguesActionPerformed
        MensagensUtil.setLocale(MensagensUtil.LOCALE_PT_BR);
        setProperties();
    }//GEN-LAST:event_menuPortuguesActionPerformed

    private void menuInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInglesActionPerformed
        MensagensUtil.setLocale(MensagensUtil.LOCALE_EN_US);
        setProperties();
    }//GEN-LAST:event_menuInglesActionPerformed

    private void menuEspanholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEspanholActionPerformed
        MensagensUtil.setLocale(MensagensUtil.LOCALE_ES_ES);
        setProperties();
    }//GEN-LAST:event_menuEspanholActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuAluno;
    private javax.swing.JMenuItem menuCadastrarAluno;
    private javax.swing.JMenuItem menuEspanhol;
    private javax.swing.JMenuItem menuIngles;
    private javax.swing.JMenu menuLinguagem;
    private javax.swing.JMenuItem menuListarTurma;
    private javax.swing.JMenuItem menuPortugues;
    private javax.swing.JMenuItem menuRelatorioAlunos;
    private javax.swing.JMenuItem menuRelatorioTurmas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuTurma;
    private javax.swing.JTable tableAlunos;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
