/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.projetomap.view;

import br.edu.projetomap.dao.AlunoDAO;
import br.edu.projetomap.dao.TurmaDAO;
import br.edu.projetomap.model.Aluno;
import br.edu.projetomap.model.Turma;
import br.edu.projetomap.util.DateUtil;
import br.edu.projetomap.util.MensagensUtil;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rogerio
 */
public class AlunoJFrame extends javax.swing.JFrame {

    private AlunosJFrame alunosJFrame;
    private AlunoDAO alunoDAO = new AlunoDAO();
    private TurmaDAO turmaDAO = new TurmaDAO();
    private Turma turmaSelecionada;
    /**
     * Creates new form AlunoJFrame
     */
    public AlunoJFrame(AlunosJFrame parent) {
        this.alunosJFrame = parent;
        initComponents();
        preencherTabela(null);
        preencherDados();
    }
    
    public void preencherDados(){
        Aluno alunoSelecionado = alunosJFrame.getAlunoSelecionado();

        if (alunoSelecionado != null) {
            lblTitulo.setText("Editar Aluno");
            txtCPF.setText(alunoSelecionado.getCpf());
            txtNome.setText(alunoSelecionado.getNome());
            txtTelefone.setText(alunoSelecionado.getTelefone());
//            txtDataNascimeto.setText(DateUtil.dateToString(alunoSelecionado.getDataNascimento()));
            txtTurmaID.setText(String.valueOf(alunoSelecionado.getTurma().getId()));
        } else {
            lblTitulo.setText("Novo Aluno");
        }
    }
    
    public void preencherTabela(List<Turma> param) {

        try {

            List<Turma> lista = (param == null) ? turmaDAO.listar() : param;

            DefaultTableModel model = new DefaultTableModel();

            model.setColumnCount(4);
            model.setColumnIdentifiers(new String[]{
                "CPF", "NOME DO PROFESSOR", "TIPO", "AULA"});
            model.setRowCount(lista.size());

            for (int i = 0; i < lista.size(); i++) {
                model.setValueAt(lista.get(i).getId(), i, 0);
                model.setValueAt(lista.get(i).getNomeProfessor(), i, 1);
                model.setValueAt(lista.get(i).getTipo(), i, 2);
                model.setValueAt(lista.get(i).getAula(), i, 3);
            }

            tableTurmas.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtTurmaID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTurmas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblTitulo.setText("Novo Aluno");

        jLabel2.setText("CPF: ");

        jLabel3.setText("Nome: ");

        jLabel4.setText("Telefone: ");

        jLabel6.setText("Id Turma: ");

        txtCPF.setToolTipText("Apenas Numero");

        txtNome.setToolTipText("");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTelefone.setToolTipText("");

        txtTurmaID.setToolTipText("");

        tableTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTurmasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTurmas);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTurmaID, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTurmaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTurmasMouseClicked

        // retorna a linha da tabela onde o clique ocorreu
        int row = tableTurmas.rowAtPoint(evt.getPoint());
        // retorna o código do cliente selecionado
        Long id = (Long) tableTurmas.getModel().getValueAt(row, 0);

        try {
            turmaSelecionada = turmaDAO.buscarPorID(id);

            System.out.println(turmaSelecionada);

        } catch (Exception e) {
            e.printStackTrace();
        }
        txtTurmaID.setText(String.valueOf(turmaSelecionada.getId()));
    }//GEN-LAST:event_tableTurmasMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {

            Aluno aluno = alunosJFrame.getAlunoSelecionado();

            if (aluno != null) {

                String cpf = txtCPF.getText();
                String nome = txtNome.getText();
                String telefone = txtTelefone.getText();
//                Date dataNascimento = DateUtil.stringToDate(txtDataNascimeto.getText());
                Turma turma = turmaDAO.buscarPorID(Long.parseLong(txtTurmaID.getText()));
                // validar!

                aluno.setCpf(cpf);
                aluno.setNome(nome);
                aluno.setTelefone(telefone);
//                aluno.setDataNascimento(dataNascimento);
                aluno.setTurma(turma);

                alunoDAO.editar(aluno, turma);

                alunosJFrame.setAlunoSelecionado(null);

            } else {

                aluno = new Aluno();

                String cpf = txtCPF.getText();
                String nome = txtNome.getText();
                String telefone = txtTelefone.getText();
//                Date dataNascimento = DateUtil.stringToDate(txtDataNascimeto.getText());
                Turma turma = turmaDAO.buscarPorID(Long.parseLong(txtTurmaID.getText()));
                // validar!

                aluno.setCpf(cpf);
                aluno.setNome(nome);
                aluno.setTelefone(telefone);
//                aluno.setDataNascimento(dataNascimento);
                aluno.setTurma(turma);

                alunoDAO.inserir(aluno, turma);

            }

            alunosJFrame.preencherTabela(null);

            dispose();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, MensagensUtil.getString(MensagensUtil.MSG_ERR0_SALVAR));
        }
    }//GEN-LAST:event_btnSalvarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableTurmas;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTurmaID;
    // End of variables declaration//GEN-END:variables
}
